# Generated by Django 3.2 on 2021-10-01 04:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='profileImage')),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userType', models.IntegerField(default=1)),
                ('pswd', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('date', models.CharField(default='', max_length=32)),
                ('details', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brands_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=64)),
                ('brand_id', models.CharField(default='', max_length=32)),
                ('created_date', models.CharField(default='', max_length=32)),
                ('updated_date', models.CharField(default='', max_length=32)),
                ('deleted_status', models.CharField(default='False', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_createdby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_deletedby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=32)),
                ('category_id', models.CharField(default='', max_length=32)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('created_date', models.CharField(default='', max_length=32)),
                ('updated_date', models.CharField(default='', max_length=32)),
                ('deleted_status', models.CharField(default='False', max_length=32)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_createdby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_deletedby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('email', models.CharField(default='', max_length=32)),
                ('phone', models.CharField(default='', max_length=32)),
                ('subject', models.CharField(default='', max_length=100)),
                ('details', models.CharField(default='', max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('description', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('delete_status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryTypes_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('gallerytype_id', models.CharField(default='', max_length=32)),
                ('date', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=64)),
                ('product_id', models.CharField(blank=True, max_length=32, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('product_image_main', models.ImageField(blank=True, null=True, upload_to='product')),
                ('price', models.FloatField(default=0.0)),
                ('product_description', models.CharField(blank=True, max_length=200, null=True)),
                ('product_details', models.CharField(blank=True, max_length=200, null=True)),
                ('product_priority', models.CharField(blank=True, max_length=32, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_status', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildApp.brands_tb')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildApp.category_tb')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_createdby', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_deletedby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GetPrice_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('phone', models.CharField(default='', max_length=32)),
                ('city', models.CharField(default='', max_length=100)),
                ('details', models.CharField(default='', max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildApp.products_tb')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('brand_name', models.CharField(default='', max_length=100)),
                ('gallery', models.ImageField(upload_to='gallery')),
                ('latest_product', models.ImageField(upload_to='gallery')),
                ('description', models.CharField(default='', max_length=200)),
                ('gallery_type', models.CharField(default='', max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_createdby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
