# Generated by Django 3.2 on 2021-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildApp', '0003_gallery_gallery_side1'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('index_image', models.ImageField(blank=True, null=True, upload_to='index')),
            ],
        ),
    ]
