# Generated by Django 3.2 on 2021-10-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildApp', '0004_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='index_tb',
        ),
    ]
