# Generated by Django 3.2 on 2021-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildApp', '0005_rename_index_index_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus_tb',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
