# Generated by Django 3.2 on 2021-10-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildApp', '0006_contactus_tb_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus_tb',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus_tb',
            name='details',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactus_tb',
            name='email',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='contactus_tb',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='contactus_tb',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='contactus_tb',
            name='response_status',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='contactus_tb',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
